src/Conversion/ONNXToTOSA/ConvertONNXToTOSA.cpp, src/Conversion/ONNXToTOSA/Math/Conv2D.cpp, src/Conversion/ONNXToTOSA/ONNXToTOSACommon.hpp, test/mlir/conversion/onnx_to_tosa/Math/Conv.mlir
Some networks may have group convolutions where the group is small, so we'd like to be able to control when to decompose those into `tosa.conv2d` and when not to.
=> feat: add a threshold to control when to decompose a grouped convolution.

src/Conversion/ONNXToTOSA/Math/Conv2D.cpp, test/mlir/conversion/onnx_to_tosa/Math/Conv.mlir
The priority is given to the decomposition of Grouped convolution into `tosa.conv2d`s, and if the threshold is exceeded, we check for the possibility of `depthwise` convolution.
=> feat: Group convolution to Depthwise convolution.

src/Conversion/ONNXToTOSA/Math/Elementwise.cpp, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir
We used to lower `"onnx.Mul"(%arg0, %arg1) : (tensor<13x21x1xf32>, tensor<21x1xf32>)` into `tosa.mul (tensor<13x21x1xf32>, tensor<21x1xf32>) -> tensor<13x21x1xf32>`, which is not allowed (ranks mismatch on tosa)
=> Fix lowering of ONNX.Mul to tosa.mul when rank-broadcasting

src/Conversion/ONNXToTOSA/DialectBuilder.cpp, src/Conversion/ONNXToTOSA/DialectBuilder.hpp, src/Conversion/ONNXToTOSA/Math/Elementwise.cpp, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir
Uses `pow(input, 0.5)` which is the same used by `TorchToTosa`.
=> feat(ONNXTOTosa): legalization sqrt.

src/Transform/ONNX/Decompose.cpp, test/mlir/onnx/onnx_decompose.mlir
This is a minor change to align the decomposition of Hardswish with `torch-mlir`.
=> fix: align decomposition of Hardswish with torch-mlir implementation.

src/Conversion/ONNXToTOSA/CMakeLists.txt, src/Conversion/ONNXToTOSA/ConvertONNXToTOSA.cpp, src/Conversion/ONNXToTOSA/ONNXToTOSACommon.hpp, src/Conversion/ONNXToTOSA/Tensor/Tile.cpp, test/mlir/conversion/onnx_to_tosa/Tensor/Tile.mlir
* Lowering can only be done if the input is ranked
* The repetitions need to be constant
=> Add ONNX to TOSA lowering for onnx.Tile

src/Dialect/ONNX/Rewrite.cpp, test/mlir/onnx/onnx_canonicalization.mlir
Reconfigure the onnx level rewrite that decides for whole-valued power exponents if the power is rewritten as multiplications. Opt to only rewrite to a multiplication if the exponent is 2.
=> Avoid generating chains of multiplications

src/Dialect/Mlir/IndexExprBuilder.cpp, src/Dialect/ONNX/ONNXOps.td.inc, src/Dialect/ONNX/ONNXOps/OpHelper.cpp, test/mlir/onnx/onnx_canonicalization.mlir
For certain operations we require upstream type support. The current list of operations are: Conv, MaxPool, AveragePool and GlobalAveragePool. For now we will manually modified the TD file to add support while we wait. 
These manual changes should be removed once the upstream definition has been approved and updated. This is only a temporary solution for now to get a bfloat16 flow to run with CNNs.
Also added a fix to the Pow optimization where the exponent was a bf16 scalar constant.
=> feat(ONNXOps): add manual bfloat16 support

src/Conversion/ONNXToTOSA/NN/MaxPoolSingleOut.cpp, test/mlir/conversion/onnx_to_tosa/NN/MaxPoolSingleOut.mlir
Up to now, we only supported MaxPool when the dilations attribute is absent, which means that the default dilations of `1` in each dimension is used.
Now we also allow when the dilations are explicitly specified as `1`.
=> ONNXToTosa: MaxPoolSingleOut: Support dilations whens they are 1

src/Conversion/ONNXToTOSA/ConvertONNXToTOSA.cpp, src/Conversion/ONNXToTOSA/Math/Elementwise.cpp, src/Conversion/ONNXToTOSA/ONNXToTOSACommon.hpp, src/Conversion/ONNXToTOSA/Tensor/Resize.cpp, src/Conversion/ONNXToTOSA/Tensor/Transpose.cpp, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir, utils/clone-mlir.sh
Those are not allowed by the TOSA spec, but they are allowed by the TOSA dialect.
And ONNX allows them, so we need to lower them somehow.
=> ONNXToTosa: Allow unsigned integers

src/Conversion/ONNXToTOSA/Math/Softmax.cpp, test/mlir/conversion/onnx_to_tosa/Math/Softmax.mlir
Both versions are identical for small inputs, but the new version avoids overflow for large input tensor values.
See https://stackoverflow.com/a/34969389/20356323
=> ONNXToTOSA: Use numerical stable lowering of Softmax

src/Conversion/ONNXToTOSA/Tensor/Gather.cpp, test/mlir/conversion/onnx_to_tosa/Tensor/Gather.mlir
We used to require that the indices are constant. Now we also allow non-constant indices.
The main complication is that ONNX allows negative indices and TOSA doesn't. Thus we need to emit a few tosa ops to turn negative indices into positive ones by adding the size of the gathered dimension.
=> ONNXToTOSA: Gather: Support non-constant indices

src/Conversion/ONNXToTOSA/DialectBuilder.cpp, src/Conversion/ONNXToTOSA/Math/Elementwise.cpp, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir
ONNX.Cast has truncating behavior, and tosa.cast has rounds half-to-even.
We simulate truncate by floor for positive values and ceil for negative
ones.
=> ONNXToTOSA: Fix rounding for Cast from float to int

src/Compiler/CMakeLists.txt, src/Compiler/CompilerOptions.cpp, src/Compiler/CompilerOptions.hpp, src/Compiler/CompilerUtils.cpp, test/mlir/driver/bytecode.mlir
This improves speed and reduces the size.
=> Compiler: Allow to emit IR as bytecode

src/Transform/ONNX/Decompose.cpp, test/mlir/onnx/onnx_decompose.mlir
In some of our examples we have group and instance normalization fail the decomposition due to unknown shapes at the time of decomposition. But due to the onnx-mlir pipeline and the iterative execution of passes, we can allow the operations after decomposition.
Meaning that during the next execution of the decomposition pass we can decompose the operations as shape inference has executed and resolved the input shapes as static.
=> Allow Group and Instance Normalization after Decomposition

.github/workflows/macos-amd64-build.yml
The macos-latest version is macos 14 that removed python 3.10, so it failed to install protobuf 4.21.12 using python 3.11 or 3.12 in macos 14.
Picked from https://github.com/onnx/onnx-mlir/pull/2816
=> Fix macos build by pinning version

.github/workflows/macos-amd64-build.yml, utils/install-onnx-mlir.sh
Brings the CI time to 10 minutes.
Only build on pushes to the main/feature branch. Otherwise every PR sees two builds because pushing to the PR branch and changing the pull_request both trigger it separate builds.
Introduce ccache to speed-up onnx-mlir builds.
=> Add ccache / don't run action twice on pull_requests

src/Conversion/ONNXToTOSA/DialectBuilder.cpp, src/Conversion/ONNXToTOSA/DialectBuilder.hpp, src/Conversion/ONNXToTOSA/Tensor/Squeeze.cpp, test/mlir/conversion/onnx_to_tosa/Tensor/Squeeze.mlir, test/mlir/conversion/onnx_to_tosa/Tensor/Unsqueeze.mlir
While we were talking about it, I realized that we can do the reshape trick here, too.
=> ONNXToTOSA: Support Squeeze/Unsqueeze with runtime shape operand

src/Builder/FrontendDialectTransformer.cpp, src/Conversion/ONNXToTOSA/Math/Elementwise.cpp, test/mlir/onnx/parse/cast_with_saturate.onnxtext
While investigating why some test case don't have error messages, I found a fix for this crash.
The Cast op got a new attribute `saturate`, but the ONNX to onnx-mlir parse assumed that all attributes on the Cast op are data types (and not a boolean like for saturate).
=> FrontendDialectTransformer: Don't crash when importing Cast with saturate attribute

src/Conversion/ONNXToTOSA/DialectBuilder.cpp, src/Conversion/ONNXToTOSA/Math/Elementwise.cpp, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir
We don't need to be strict in the lowering as the TOSA dialect was extended to allow all integer types.
=> ONNXToTosa: Fix integer division for != 32 bits

src/Conversion/ONNXToTOSA/NN/QuantizeLinear.cpp, test/mlir/conversion/onnx_to_tosa/NN/QuantizeLinear.mlir
Converting the IR from doing 
`y = saturate((x / y_scale)) + y_zero_point`
to do
`y = saturate((x / y_scale) + y_zero_point)`
as stated in the [doc](https://onnx.ai/onnx/operators/onnx__QuantizeLinear.html)
=> QLinear saturate last

src/Conversion/ONNXToTOSA/Math/Elementwise.cpp, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir
The TOSA MLIR bindings have [Sin](https://mlir.llvm.org/docs/Dialects/TOSA/#tosasin-mlirtosasinop) and [Cos](https://mlir.llvm.org/docs/Dialects/TOSA/#tosacos-mlirtosacosop) operations, so lower to them instead of `CustomOp`
=> Lower cos and sin to tosa::SinOp/CosOp instead of tosa::CustomOp

src/Conversion/ONNXToTOSA/Math/Elementwise.cpp, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir
Employ the `SameOperandsAndResultElementType` before the operator is created. Unfortunately, I can employ `verifySameOperandsAndResultElementType` since the operator hasn't been created.
=> Avoid converting to TOSA if the invariants are not respected

src/Dialect/ONNX/ONNX.td, src/Dialect/ONNX/ONNXOps.hpp, src/Dialect/ONNX/ONNXOps.td.inc, src/Dialect/ONNX/ONNXTraits.hpp, utils/gen_onnx_mlir.py
This PR modifies the op definition (.td) to add the op version as an explicit trait. Downstream passes can use this trait and not make assumptions on the ONNX-MLIR opset version.
=> [FXML-4647] Add ONNX operator version as trait of dialect

src/Builder/FrontendDialectTransformer.cpp, test/mlir/onnx/parse/com.microsoft.qdq_linear.json
https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md lists operations that Microsoft has contributed to onnxruntime. The current intent of onnx-mlir is that these should be imported as `onnx.Custom` operations. However there were 2 issues:
- as some `com.microsoft` domain operations have the same names as `ai.onnx` (default) domain operations, they were incorrectly imported as the latter.
- the shape inference of some operations is different to the default shape inference for custom operations. The custom op shape inference has attributes that can express what is needed for `com.micosoft.{QuantizeLinear,DequantizeLinear}` but I cannot find a mechanism to specify these should be set for an operation. For now I'm hard-coding setting these until I work out how to do …
=> Provided hard-coded shape annotations for some com.microsoft operations

src/Builder/FrontendDialectTransformer.cpp, src/Dialect/ONNX/ONNXOps/ShapeHelper.cpp, src/Dialect/ONNX/Transforms/SetONNXNodeName.cpp
Because we use stdout to print the IR bytecode. Otherwise the bytecode gets mixed with warning messages and causes the parsing of the byte code to crash.
=> Output warnings/errors to stderr

src/Dialect/ONNX/AdditionalONNXOps.td
Two ONNX-MLIR ops correspond to special cases of existing ops:
* ONNXMaxPoolSingleOutOp
* ONNXBatchNormalizationInferenceModeOp
This PR gives version number to these ops matching the version numbers of the op they're a special case of. Drawback: these need to be manually updated each time the opset is re-generated...
=> Include op version in additional ops that have one

src/Conversion/ONNXToTOSA/Math/Conv2D.cpp, src/Conversion/ONNXToTOSA/Math/MatMul.cpp, src/Conversion/ONNXToTOSA/Tensor/Flatten.cpp, test/mlir/conversion/onnx_to_tosa/Math/Conv.mlir, test/mlir/conversion/onnx_to_tosa/Tensor/Flatten.mlir
We should avoid trying to convert onnx to tosa when dyn shapes for Flatten and Conv2d.
=> fix: don't lower Conv2D and Flatten with dynamic shapes.

src/Dialect/ONNX/Transforms/ConstProp.cpp, src/Dialect/ONNX/Transforms/ConstProp.td, test/mlir/onnx/onnx_constprop.mlir
We now support: `bitwise_(not/and/or), logical_(not,and,or,xor), clip, ceil, floor, sin, cos, log, erf, exp, not`.
I will open a PR upstream in the coming weeks.
=> feat: add constant propagation for different unary and binary ops.

src/Conversion/ONNXToTOSA/DialectBuilder.cpp, src/Conversion/ONNXToTOSA/DialectBuilder.hpp, src/Conversion/ONNXToTOSA/Math/Elementwise.cpp, src/Conversion/ONNXToTOSA/Math/Gemm.cpp, src/Conversion/ONNXToTOSA/Math/Reduce.cpp, src/Conversion/ONNXToTOSA/NN/AveragePool.cpp, src/Conversion/ONNXToTOSA/NN/BatchNorm.cpp, src/Conversion/ONNXToTOSA/ONNXToTOSACommon.cpp, src/Conversion/ONNXToTOSA/ONNXToTOSACommon.hpp.inc, src/Conversion/ONNXToTOSA/Tensor/Gather.cpp, src/Conversion/ONNXToTOSA/Tensor/PaddingOp.cpp, src/Conversion/ONNXToTOSA/Tensor/Shrink.cpp, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir, test/mlir/conversion/onnx_to_tosa/Tensor/Gather.mlir
It is safer to make `dtype` a required argument of `TosaBuilder::getSplattedConst` since we might miss to specify it in some cases.
This PR is specifically motivated by ONNXToTosa lowering of `onnx.Cast` where we weren't passing on the `dtype` and `onnx.cast` conversion for `f16` types were generating illegal code (`tosa.greater_than` was getting created with `f16` and `f32`).
So the intent of this change is so that we don't miss it anymore.
=> feat: make dtype a required argument of TosaBuilder::getSplattedConst.

src/Dialect/ONNX/ONNXOps/OpHelper.cpp, src/Dialect/ONNX/ONNXOps/Tensor/Reshape.cpp, test/mlir/onnx/onnx_shape_inference.mlir
The problem was that the check:
```
if ((getShape(vType)[0] == 1) && getElementType(vType).isSignlessInteger(64))
return true;
```
can succeed even if `areDims(Value val)` is not true for all operands of Concat. 
I think this should be upstreamed
=> Fix crash in ReshapeOp inference when an input to the previous concat is empty

src/Dialect/ONNX/ONNXOps/OpHelper.cpp, src/Dialect/ONNX/ONNXOps/Tensor/Reshape.cpp, test/mlir/onnx/onnx_shape_inference.mlir
=> Backport: Fix crash in ReshapeOp inference when an input to the previous concat is empty

src/Conversion/ONNXToTOSA/ConvertONNXToTOSA.cpp, src/Conversion/ONNXToTOSA/Tensor/Gather.cpp, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir, test/mlir/conversion/onnx_to_tosa/Tensor/Gather.mlir
Lowering to tosa was failing when Elementwise binary had dynamic type saying that `shape` dialect was not loaded. The pass must add `ShapeDialect` as its dependent dialects.
Also, Gather shouldn't fail when indices are dynamic type. For now, no lower to TOSA is done.
=> fix: do not fail when using dynamic types in Binary ElemWise and Gather.

src/Dialect/ONNX/Transforms/Decompose.cpp, test/mlir/onnx/onnx_decompose.mlir
Checks that the Input and Output of InstanceNormalizationOp and GroupNormalizationOp have a static shape before trying to decompose them
I will backport this to release too
=> Fix a crash in the Decomposition of InstanceNormalizationOp and GroupNormalizationOp  if they have a dynamic shape

src/Dialect/ONNX/Transforms/Decompose.cpp, test/mlir/onnx/onnx_decompose.mlir
=> Backport: Fix a crash in the Decomposition of InstanceNormalizationOp and GroupNormalizationOp if they have a dynamic shape 

src/Dialect/ONNX/ONNXOps/ShapeHelper.cpp, src/Dialect/ONNX/ONNXOps/Tensor/Squeeze.cpp, src/Dialect/ONNX/Transforms/ShapeInference.cpp, test/mlir/onnx/onnx_canonicalization.mlir, test/mlir/onnx/onnx_canonicalization_without_shape_inference.mlir, test/mlir/onnx/onnx_shape_inference.mlir, test/mlir/onnx/onnx_shape_inference_error.mlir
As a reminder, `If axes is not provided, all the single dimensions will be removed from the shape.`.
THis PR also decouples shape inference for Squeeze from folding, and I had to make changes on the tests to cope with that: changing some LIT tests to get the right shapes inferred, and separated some other tests that were failing or giving wrong shape inference.
=> feat: allow Squeeze to infer shape of tensor with single dynamic dimension when axes is not provided.

src/Conversion/ONNXToTOSA/Tensor/Gather.cpp, test/mlir/conversion/onnx_to_tosa/Tensor/Gather.mlir
This simplifies the special case where you gather one specific row/column/..., i.e., effectively dropping everything else in a dimension (making it redundant/1). Since a slice in TOSA is rank-preserving, we generate it with the 1-dimension, and add a reshape afterwards to get rid of it. See the added tests for examples.
=> [FXML-4790] Simplify some gathers to slices

src/Conversion/ONNXToTOSA/NN/AveragePool.cpp, test/mlir/conversion/onnx_to_tosa/NN/AveragePool.mlir
The `createOrderedPadAttrForWindowBasedOps` just before the new check would create a `pad` operation assuming rank 4 (i.e. 2d average pool + channel and batch dimension) and then crash in the tosa.pad shape inference.
This makes sure that we don't go there.
=> ONNXToTOSA: Don't crash on 3d average pool

src/Conversion/ONNXToTOSA/NN/QuantizeLinear.cpp, src/Conversion/ONNXToTOSA/ONNXToTOSALegalizeUtils.hpp, test/mlir/conversion/onnx_to_tosa/NN/QuantizeLinear.mlir
- If the zero point is of NoneType avoid doing the add
- If the resulting type is integer the intermediate computation needs to be rounded before adding the zero point
=> Fix QuantizeLinear for two cases

src/Conversion/ONNXToTOSA/NN/QuantizeLinear.cpp, src/Conversion/ONNXToTOSA/ONNXToTOSALegalizeUtils.hpp, test/mlir/conversion/onnx_to_tosa/NN/QuantizeLinear.mlir
Port to release branch from https://github.com/Xilinx/onnx-mlir/pull/138
Fixes numeric mismatches when zero-point is non-zero in x86.
=> Fix QLinear release branch

src/Conversion/ONNXToTOSA/NN/QuantizeLinear.cpp, test/mlir/conversion/onnx_to_tosa/NN/QuantizeLinear.mlir
Per ONNX doc:
> The quantization formula is y = saturate((x / y_scale) + y_zero_point).
This commit introduces the saturation for integer types. Computations are performed using 32 bits (wider than all supported integer types), so we can introduce a clamp before the cast to the destination type is performed.
=> [FXML-4819] Clamp QuantizeLinear to integers

src/Dialect/ONNX/ONNXOps.td.inc, src/Dialect/ONNX/ONNXOps/Tensor/EyeLike.cpp, test/mlir/onnx/parse/eyelike.onnxtext, test/mlir/onnx/parse/eyelike_dtype.onnxtext, utils/gen_onnx_mlir.py
This adds result type inference for onnx.EyeLike
The onnx standard is a bit unclear when it comes to the resulting type of `EyeLike`.
It states:
>  **dtype - INT :**
> 
> (Optional) The data type for the elements of the output tensor. If not specified,the data type of the input tensor T1 is used. If input tensor T1 is also notspecified, then type defaults to ‘float’.
But the input T1 is required, so it is unclear how/why the case that requires a defaulting to 'float' can happen. For this reason I did not add support for the defaulting to 'float'.
Without the changes in this PR, the `EyeLike` in the added test has an output type of  `none`. In a larger model this leads to an error in the verifier, but I was not able to reproduce this in a small test
=> Add result type inference for onnx.EyeLike

src/Dialect/ONNX/Transforms/ConstProp.cpp, src/Dialect/ONNX/Transforms/ConstProp.td, test/mlir/onnx/onnx_constprop.mlir
`Abs` requires a disambiguation of the `std::abs` function for integer types, otherwise the compiler doesn't know which function to use.
`Round` implements `roundeven`, which isn't part of the C++ std, but only from C23. Therefore, it isn't a one-to-one translation of `std::round`.
=> feat: Constant propagation for ONNXAbsOp and ONNXRoundOp.

src/Builder/FrontendDialectTransformer.cpp, test/mlir/onnx/parse/test_dim_zero.onnxtext
ONNX allows dimensions to have zero size. Before this PR, those were imported as dynamic dimensions, but they must be imported as static.
=> Import ONNX models where some dimensions have zero size

src/Conversion/ONNXToTOSA/Tensor/Expand.cpp, test/mlir/conversion/onnx_to_tosa/Tensor/Expand.mlir
This is the root cause of a bug seen in recent model runs `failed to materialize conversion for result #0 of operation onnx.X `
=> Fix Expand shape computation when one dim is bigger than its tiling
